### PR TITLE
feat: add braindigit IT solution

### PR DESCRIPTION
**Pull request by aayush105**
## What kind of change does this PR introduce? 

- [ ] Bug Fix
- [ ] Documentation change
- [x] Added new company
- [ ] Other(s)

### CODE REVIEW

**Review by drishyakarki — APPROVED** [review]
LGTM

**Comment by aayush105** [comment]
@thenishantsapkota  why it is marked as invalid label? which information seems wrong to you? Can provide the review?

**Comment by thenishantsapkota** [comment]
This was incorrectly merged!
The phone number format isn't correct @aayush105

**Comment by aayush105** [comment]
> This was incorrectly merged! The phone number format isn't correct @aayush105

@thenishantsapkota Is incorrect format is considered as a incorrect/wrong infomartion? It was reviewed by one of your member and merge it, at the time of merging they could have request changes if the formate is wrong.

**Comment by thenishantsapkota** [comment]
I'm sorry for the inconvenience. I was meant to review it but before reviewing, the pr was merged. I forgot to mention you about it. The correct format is `+977-1xxxxxx`

**Comment by thenishantsapkota** [comment]
I'm sorry for the inconvenience. I was meant to review it but before reviewing, the pr was merged. I forgot to mention you about it. The correct format is `+977-1xxxxxx`
You can open another PR fixing these changes.

**Comment by aayush105** [comment]
> I'm sorry for the inconvenience. I was meant to review it but before reviewing, the pr was merged. I forgot to mention you about it. The correct format is `+977-1xxxxxx` You can open another PR fixing these changes.

But one of the PR is already resolved and marked as invalid, what can be done in that case?

**Comment by thenishantsapkota** [comment]
> > I'm sorry for the inconvenience. I was meant to review it but before reviewing, the pr was merged. I forgot to mention you about it. The correct format is `+977-1xxxxxx` You can open another PR fixing these changes.
> 
> But one of the PR is already resolved and marked as invalid, what can be done in that case?

You can just open another PR from the main branch to fix those changes. The label for the other PRs will be unchanged.

**Comment by aayush105** [comment]
> > > I'm sorry for the inconvenience. I was meant to review it but before reviewing, the pr was merged. I forgot to mention you about it. The correct format is `+977-1xxxxxx` You can open another PR fixing these changes.
> > 
> > 
> > But one of the PR is already resolved and marked as invalid, what can be done in that case?
> 
> You can just open another PR from the main branch to fix those changes. The label for the other PR will be changed. You would only open 1 PR to update those so it shouldn't matter much.
> 
> You can make another PR to fix the format for this PR

@thenishantsapkota can you check it i have created a PR.

**Pull request merged**
