### PR TITLE
Added TAI Inc.

### PR DESCRIPTION
**Pull request by Anupamaraie**
## What kind of change does this PR introduce? 

- [ ] Bug Fix
- [ ] Documentation change
- [x] Added new company
- [ ] Other(s)

### CODE REVIEW

**Review by drishyakarki — CHANGES_REQUESTED** [review]
Please remove the trailing commas at line 785 and 789

**Review by thenishantsapkota — CHANGES_REQUESTED** [review]
Please properly format the code using prettier

**Comment by Anupamaraie** [comment]
Done!

**Review by thenishantsapkota — APPROVED** [review]
LGTM!
Thank you for your contribution @Anupamaraie

**Review by drishyakarki — APPROVED** [review]
LGTM

**Pull request merged**
